package io.github.khezyapp.api.audit.extractor;

import io.github.khezyapp.api.audit.api.SensitiveMasker;
import jakarta.servlet.http.HttpServletRequest;
import org.aopalliance.intercept.MethodInvocation;
import org.springframework.http.MediaType;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Implementation of {@link AbstractBodyExtractor} that handles standard URL-encoded form submissions.
 * <p>
 * This extractor processes requests with the {@code application/x-www-form-urlencoded} content type,
 * typically generated by standard HTML form submissions. It flattens the parameter map into a
 * single-level map, handling single and multiple value scenarios for each form field.
 * </p>
 */
public class FormBodyExtractor extends AbstractBodyExtractor {

    /**
     * Constructs a new form body extractor with the specified sensitive data masker.
     *
     * @param sensitiveMasker the masker to apply to extracted form values
     */
    public FormBodyExtractor(final SensitiveMasker sensitiveMasker) {
        super(sensitiveMasker);
    }

    /**
     * Determines if this extractor supports the given request and method invocation.
     * <p>
     * Support is granted if the request is non-null and the {@code Content-Type}
     * header is compatible with {@link MediaType#APPLICATION_FORM_URLENCODED}.
     * </p>
     *
     * @param invocation the current method invocation
     * @param request the current HTTP servlet request
     * @return {@code true} if the request is a standard form submission, {@code false} otherwise
     */
    @Override
    public boolean supports(final MethodInvocation invocation,
                            final HttpServletRequest request) {
        return Objects.nonNull(request) && isContentType(request, MediaType.APPLICATION_FORM_URLENCODED);
    }

    /**
     * Extracts parameters from the URL-encoded request body.
     * <p>
     * The extraction logic simplifies the {@code ServletRequest#getParameterMap()}:
     * <ul>
     * <li>Empty value arrays are mapped as {@code null}.</li>
     * <li>Arrays with a single element are mapped directly to that element.</li>
     * <li>Arrays with multiple elements are kept as an array.</li>
     * </ul>
     * </p>
     *
     * @param invocation the current method invocation
     * @param request the current HTTP servlet request
     * @return a map of form parameter names and their simplified values
     */
    @Override
    protected Map<String, Object> doExtract(final MethodInvocation invocation,
                                            final HttpServletRequest request) {
        final var params = new LinkedHashMap<String, Object>();
        for (final var entry : request.getParameterMap().entrySet()) {
            final var value = entry.getValue();
            if (value.length == 0) {
                params.put(entry.getKey(), null);
            } else if (value.length == 1) {
                params.put(entry.getKey(), value[0]);
            } else {
                params.put(entry.getKey(), value);
            }
        }
        return params;
    }
}
