package io.github.khezyapp.api.audit.api;

import io.github.khezyapp.api.audit.model.AuditEntityChange;
import io.github.khezyapp.api.audit.model.AuditLogRecord;

/**
 * Service interface for processing and persisting audit log events.
 * <p>
 * This service acts as the central dispatcher for two types of audit data:
 * <ul>
 * <li><b>Request-based logs:</b> High-level metadata captured from method
 * invocations (e.g., API calls, user actions).</li>
 * <li><b>Entity-based logs:</b> Detailed data-level changes captured
 * during database persistence cycles.</li>
 * </ul>
 * </p>
 */
public interface AuditLogService {

    /**
     * Processes a high-level audit record generated by an interceptor or aspect.
     * <p>
     * This method typically handles metadata such as the action performed,
     * the user's IP address, the request URI, and the success/failure status
     * of the operation.
     * </p>
     *
     * @param auditLogRecord the structured record containing request and execution metadata
     */
    void onRequest(AuditLogRecord<?> auditLogRecord);

    /**
     * Processes fine-grained entity state changes captured during the data access layer lifecycle.
     * <p>
     * This method is invoked when an entity is created, updated, or deleted,
     * providing a detailed list of field-level differences (from/to values).
     * </p>
     *
     * @param auditEntityChange the object containing the diff of entity field changes
     */
    void onAuditEntityChanges(AuditEntityChange auditEntityChange);
}
